server.port=8761
spring.application.name=eureka-server

# Eureka Server Configuration
eureka.instance.hostname=localhost
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=5000

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
