apiVersion: v1
kind: ConfigMap
metadata:
  name: edusubmit-config
  namespace: edusubmit-production
data:
  SPRING_PROFILES_ACTIVE: "production"
  SPRING_REDIS_HOST: "redis-service"
  AI_ENGINE_URL: "http://ai-service:5000"
  UPLOAD_DIR: "/app/uploads"
  NODE_ENV: "production"
